live_config_reload = true
working_directory = "None"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["-l", "-c", "tmux -f ~/.config/tmux/.tmux.conf new-session -A -s main"]
program = "/bin/zsh"

[window]
decorations = "Full"
dynamic_padding = true
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xd18616"
index = 16

[[colors.indexed_colors]]
color = "0xf97583"
index = 17

[colors.bright]
black = '0x959da5'
red = '0xf97583'
green = '0x85e89d'
yellow = '0xffea7f'
blue = '0x79b8ff'
magenta = '0xb392f0'
cyan = '0x56d4dd'
white = '0xfafbfc'

[colors.normal]
black = '0x586069'
red = '0xea4a5a'
green = '0x34d058'
yellow = '0xffea7f'
blue = '0x2188ff'
magenta = '0xb392f0'
cyan = '0x39c5cf'
white = '0xd1d5da'

[colors.primary]
background = "0x24292e"
foreground = "0xd1d5da"

