tap "arl/arl" # for git-mux

brew "fzf"
brew "stow"
brew "zoxide"
brew "ripgrep"
brew "wget"
brew "tmux"
brew "tpm"
brew "herdr"
brew "neovim"
brew "coreutils"
brew "findutils"
brew "gnu-which"
brew "gnu-tar"
brew "gnu-sed"
brew "gawk"
brew "gnutls"
brew "gnu-indent"
brew "gnu-getopt"
brew "grep"
brew "postgresql"
brew "gitmux"
brew "starship"
brew "mise"

cask "vlc"
cask "slack"
cask "discord"
cask "telegram"
cask "signal"
cask "ilok-license-manager"
cask "zed"
cask "spotify"
cask "ghostty"
cask "guitar-pro"
cask "hiddenbar"
cask "google-chrome"
cask "figma"
cask "tailscale"
cask "lm-studio"
cask "blender"
cask "hammerspoon"

# manual install required
# - logic pro
# - final cut
# - neural dsp plugins
