#! /bin/bash

usage() {
    echo "usage: $0 [stow,unstow]"
}

find_candidates() {
    CANDIDATES="$(find . -maxdepth 1 -mindepth 1  -type d ! -name ".*" \
        | grep -v deploy_helpers \
        | grep -v ignore \
        | sed 's/^\.\///g')"
}

print_candidates() {
    echo "Found $(echo "${CANDIDATES}" | wc -l) candidates: ${CANDIDATES}" \
        | awk '{printf "%s%s", (NR==1?"":", "), $0} END {print "\n"}'
}

if [ "$1" == "stow" ]; then 
    find_candidates
    print_candidates

    while IFS= read -r CANDIDATE
    do 
        echo "Stowing $CANDIDATE..."
        stow "$CANDIDATE" -t $HOME
    done <<< "${CANDIDATES}"
elif [ "$1" == "unstow" ]; then 
    find_candidates
    print_candidates

    while IFS= read -r CANDIDATE
    do 
        echo "Unstowing $CANDIDATE..."
        stow -D "$CANDIDATE" -t $HOME
    done <<< "${CANDIDATES}"
else
    usage
    exit 1
fi

echo -e "\nOperations completed successfully."

