#! /bin/env bash

function usage() {
    echo "usage: deploy [stow,unstow]"
    exit 1
}

CANDIDATES="$(find . -maxdepth 1 -mindepth 1  -type d ! -name ".*" \
    | grep -v deploy_helpers \
    | sed 's/^\.\///g')"

echo "Found: ${CANDIDATES}" \
    | awk '{printf "%s%s", (NR==1?"":", "), $0} END {print "\n"}'

if [ "$1" == "stow" ]; then 
    while IFS= read -r CANDIDATE
    do 
        echo "Stowing $CANDIDATE..."
        stow "$CANDIDATE"
    done <<< "${CANDIDATES}"
elif [ "$1" == "unstow" ]; then 
    while IFS= read -r CANDIDATE
    do 
        echo "Unstowing $CANDIDATE..."
        stow -D "$CANDIDATE"
    done <<< "${CANDIDATES}"
else
    usage
fi

echo -e "\nOperations completed successfully."

